pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                echo "Cloning the repo..."
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Running build step..."
                // For Python:
                // sh 'pip install -r requirements.txt'

                // For frontend:
                // sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                // e.g., sh 'pytest tests/' or custom script
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy stage (placeholder)..."
                // You can add FTP, SSH or Docker deployment here
            }
        }
    }
}
